checklist/urls.py
from django.urls import path

from checklist.export_view import ExportChecklistView

from . import views

app_name = "checklist"
urlpatterns = [
    path("", views.profile_view, name="start"),
    path("procedures/", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.procedure_detail, name="detailpk"),
    path("<slug:slug>", views.procedure_detail, name="detail"),
    path("profile/", views.profile_view, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("export/", ExportChecklistView.as_view(), name="export"),
    path("update-session-role/", views.update_session_role, name="update_session_role"),
]

checklist/models.py
"""
Main models module for al database objects
"""

# pylint: disable=no-member

from colorfield.fields import ColorField
from django.urls import reverse
from django.db import models


class Procedure(models.Model):
    title = models.CharField(max_length=40)
    step = models.PositiveIntegerField()
    slug = models.SlugField(unique=True)
    show_expression = models.TextField(blank=True)
    auto_continue = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title.__str__()

    def get_absolute_url(self):
        return reverse("checklist:detail", kwargs={"slug": self.slug})


class CheckItem(models.Model):
    item = models.CharField(max_length=50)
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    step = models.PositiveIntegerField()
    setting = models.CharField(max_length=80)
    action_label = models.CharField(max_length=8, blank=True)
    dataref_expression = models.TextField(blank=True)
    attributes = models.ManyToManyField(
        "Attribute", blank=True, related_name="checkItems"
    )

    ROLE_CHOICES = [
        ("PF", "Pilot Flying"),
        ("PM", "Pilot Monitoring"),
        ("C", "Captain"),
        ("BOTH", "Both"),
        ("FO", "First Officer"),
    ]
    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default="",
        blank=True,
        help_text="Indicates who should perform this check item.",
    )

    def __str__(self) -> str:
        return self.item.__str__()

    def get_action_label(self):
        if self.action_label:
            return self.action_label

        if not self.attributes.filter(title="NoActionNeed").exists():
            return "SET"
        else:
            return "CHECKED"

    def shouldshow(self, profile_list):
        attributes = self.attributes.values_list("id", flat=True)
        if attributes:
            matching = set(attributes) & set(profile_list)
            return len(matching) == len(attributes)

        # Is a mandatory checkitem as it has no attributes
        return True

    class Meta:
        ordering = ["step"]


class Attribute(models.Model):
    """
    Model for the attributes of a procedure
    The Title is the main identifier
    The order is used to sort
    """

    title = models.CharField(max_length=30)
    order = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    show = models.BooleanField(default="True")
    over_ruled_by = models.ForeignKey(
        "self", on_delete=models.SET_NULL, blank=True, null=True
    )
    btn_color = ColorField(default="#194D33")

    def __str__(self) -> str:
        return self.title.__str__()

checklist/views.py
"""
Base views for checklist
"""

from datetime import timedelta
from time import time

from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.timezone import now

# Create your views here.
from django.views import generic

from checklist.simbrief import SimBrief

from .models import Attribute, Procedure


def procedure_detail(request, slug):
    """ "
    view/function to show all checkitems and attribs for the given slug
    based on the flight profile in the session
    """
    time_start = time()
    ## get the procedure to view based on slug
    procedure2view = get_object_or_404(Procedure.objects.all(), slug=slug)

    # get next and previous procedure to fill next and back button
    # As step does not need to have increments of 1, get the first or last
    # ordered by step, filtered by current step number
    nextproc = (
        Procedure.objects.filter(step__gt=procedure2view.step).order_by("step").first()
    )
    prevproc = (
        Procedure.objects.filter(step__lt=procedure2view.step).order_by("step").last()
    )
    # print(request.)
    # Check if profile exits
    if "attrib" not in request.session:
        return HttpResponseRedirect(reverse("checklist:start"))

    allitems = procedure2view.checkitem_set.all()
    pilot_role = request.session.get("pilot_role", None)
    captain_role = request.session.get("captain_role", None)
    dual_mode = request.session.get("dual_mode", False)

    query_ids = [
        item.id for item in allitems if item.shouldshow(request.session["attrib"])
    ]
    filtered_check_items = procedure2view.checkitem_set.filter(id__in=query_ids)

    time_finished = time()
    query_time = round(time_finished - time_start, 3)

    # Annotate each item with a 'lowlight' flag
    check_items = []
    for item in filtered_check_items:
        item.lowlight = (
            dual_mode
            and item.role != "BOTH"
            and item.role not in [pilot_role, captain_role]
        )
        check_items.append(item)

    # If len(check_items) is zero and there's a next procedure, redirect to it
    if len(check_items) == 0:
        # Check if referrer is same as next
        if nextproc and (nextproc.slug in request.META["HTTP_REFERER"]):
            if prevproc:
                return HttpResponseRedirect(
                    reverse("checklist:detail", args=[prevproc.slug])
                )
        ##and nextproc is not None:
        else:
            if nextproc:
                return HttpResponseRedirect(
                    reverse("checklist:detail", args=[nextproc.slug])
                )

    context = {
        "procedure": procedure2view,
        "check_items": check_items,
        "nextproc": nextproc,
        "prevproc": prevproc,
        "proctime": query_time,
    }
    return TemplateResponse(
        request,
        "checklist/detail.html",
        context,
    )


class IndexView(generic.ListView):
    """basic class view to show all procedures"""

    template_name = "checklist/index.html"
    context_object_name = "procedure_list"

    def get_queryset(self):
        return Procedure.objects.order_by("step")


def get_simbrief_context(simbrief=None):
    """
    Extracts context fields related to SimBrief data.
    If simbrief is None, default values are returned.
    """
    return {
        "origin": getattr(simbrief, "origin", "Unknown"),
        "elevation": getattr(simbrief, "elevation", "Unknown"),
        "temperature": getattr(simbrief, "temperature", "Unknown"),
        "runway": getattr(simbrief, "runway", "Unknown"),
        "rwy_length": getattr(simbrief, "rwy_length", "Unknown"),
        "altimeter": getattr(simbrief, "altimeter", "Unknown"),
        "flap_setting": getattr(simbrief, "flap_setting", "Unknown"),
        "bleed_setting": getattr(simbrief, "bleed_setting", "Unknown"),
        "error_message": getattr(simbrief, "error_message", ""),
    }


def update_profile_with_simbrief(request, simbrief):
    """
    Update the session['attrib'] list based on SimBrief data.
    """
    # Retrieve the current attribute list from the session
    attlist = request.session.get("attrib", [])

    # Extract cleaned temperature once
    if simbrief.temperature:
        cleaned_temperature = float(simbrief.temperature.replace("°C", ""))

        # Example condition: Add attribute ID 7 if temperature is below 0°C
        if cleaned_temperature < 0:
            if 7 not in attlist:
                attlist.append(7)

        # Example condition: Add attribute ID 10 if temperature is between 0°C and 10°C
        if 0 < cleaned_temperature < 11:
            if 9 not in attlist:
                attlist.append(9)
            if 7 in attlist:
                attlist.remove(7)

        # if temperature is above 10°C, remove attribute ID 9 and 7
        if cleaned_temperature > 10:
            if 9 in attlist:
                attlist.remove(9)
            if 7 in attlist:
                attlist.remove(7)

    # if bleeds are off, add attribute ID 8
    if simbrief.bleed_setting == "OFF":
        if 8 not in attlist:
            attlist.append(8)
    else:
        if 8 in attlist:
            attlist.remove(8)

    # Update the session with the modified attribute list
    request.session["attrib"] = attlist


def update_dual_mode(request, clean=False):
    """
    Updates the 'dual_mode' value in the session based on the POST data.
    """
    if not clean:
        dual_mode = request.POST.get("dual_mode", False)
    else:
        dual_mode = False

    request.session["dual_mode"] = dual_mode


def profile_view(request):

    if request.method == "POST":
        # Handle the "Clean" action
        if "Clean" in request.POST:
            print("Cleaning session")
            request.session.flush()
            update_dual_mode(request, clean=True)

            # Check if the user wants to clear the cookie
            if request.POST.get("clear_cookie") == "1":
                response = HttpResponseRedirect(reverse("checklist:profile"))
                response.delete_cookie("simbrief_pilot_id")
                return response

    # Retrieve simbrief_pilot_id from the cookie or request.POST
    simbrief_pilot_id = None

    if "simbrief_id" in request.POST:
        simbrief_pilot_id = request.POST["simbrief_id"]
    # POST data overrides cookie
    elif "simbrief_pilot_id" in request.COOKIES:
        simbrief_pilot_id = request.COOKIES.get("simbrief_pilot_id")
    elif "simbrief_pilot_id" in request.session:
        simbrief_pilot_id = request.session["simbrief_pilot_id"]

    # Initialize simbrief object only if simbrief_pilot_id is provided
    simbrief = None
    if simbrief_pilot_id:
        simbrief = SimBrief(simbrief_pilot_id)
        simbrief.fetch_data()
        # Update the session['attrib'] list based on SimBrief data
        update_profile_with_simbrief(request, simbrief)
        request.session["simbrief_pilot_id"] = simbrief_pilot_id

    # Build the context using the extracted function
    context = {
        "attributes": Attribute.objects.order_by("order"),
        "simbrief_id": simbrief_pilot_id or "",
        **get_simbrief_context(simbrief),
    }

    # Add a cookie for simbrief_pilot_id if "remember_me" is in the GET request
    response = TemplateResponse(request, "checklist/profile.html", context)

    # Set cookie if "remember_me" is checked or if cookie already exists
    if (request.COOKIES.get("simbrief_pilot_id")) or (
        "remember_me" in request.POST and simbrief_pilot_id
    ):
        expiration_date = now() + timedelta(days=31)
        response.set_cookie(
            "simbrief_pilot_id",
            simbrief_pilot_id,
            expires=expiration_date,
            secure=True,  # Ensures the cookie is sent over HTTPS only
            httponly=True,  # Prevents JavaScript access to the cookie
            samesite="Lax",  # Restricts cross-site cookie sharing
        )
    else:
        response.delete_cookie("simbrief_pilot_id")

    return response


def update_profile(request):
    """
    function that is called when profile is submitted
    Stores profile in session
    add default attributes, that is non visible
    and removes default if related attrib is selected
    """

    attlist = []

    over_rules = {}
    non_visual_attributes = list(Attribute.objects.filter(show=False))

    for default_attrib in non_visual_attributes:
        attlist.append(default_attrib.id)
        if default_attrib.over_ruled_by:
            over_rules[default_attrib.over_ruled_by.id] = default_attrib.id

    attrset = request.POST.getlist("attributes")

    for att in attrset:
        attlist.append(int(att))
        if over_rules.get(int(att), None):
            attlist.remove(over_rules[int(att)])

    request.session["attrib"] = attlist
    update_dual_mode(request)

    return HttpResponseRedirect(reverse("checklist:index"))


def update_session_role(request):
    """
    Updates the session with the selected roles (Pilot Role and Captain Role).
    """
    if request.method == "POST":
        pilot_role = request.POST.get("pilot_role", "PM")
        captain_role = request.POST.get("captain_role", "FO")

        # Update the session with the new roles
        request.session["pilot_role"] = pilot_role
        request.session["captain_role"] = captain_role

        return JsonResponse(
            {"success": True, "pilot_role": pilot_role, "captain_role": captain_role}
        )

    return JsonResponse({"success": False}, status=400)

checklist/templates/checklist/attrib_detail.html
{% if attrib.show %}
    <li class="cl-tag" style="background-color:{{ attrib.btn_color }};">{{ attrib.title }}</li>
{% endif %}

checklist/templates/checklist/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description"
              content="Training Checklist for 737 for simulation">
        <meta name="keywords" content="HTML, CSS, JavaScript">
        <meta name="author" content="ChezHJ">
        <title>
            {% block title %}
                geen titel
            {% endblock title %}
        </title>
        {% load static %}
        {% load environment_tags %}
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'checklist/style.css' %}">
        {% block script %}
        {% endblock script %}
    </head>
    <body class="body">
        <div class="content" id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="footer">
            <div class="column footer-left">
                <a class="btn btn-left btn-mid" href="{% url 'checklist:profile' %} ">Profile</a>
                Version:  {{ 'VERSION'|setting }}
                <a class="btn btn-right btn-mid"
                   href="https://github.com/chezhj/SmartTrainingChecklist/wiki/Smart-training-checklist-wiki"
                   target="_blank">Help</a>
                <br>
                simulation only
            </div>
            <div class="column footer-center">
                Made by: ChezHJ
                <br>
                By using this site you agree to the use of cookies
                <br>
                {% block footer %}
                {% endblock footer %}
            </div>
            <div class="column footer-right">
                Based on checklist by
                <br>
                <a href="https://forums.x-plane.org/index.php?/profile/136100-skymatix/"
                   target="_blank">
                    <img src="{% static 'checklist/VA_logo.png' %}"
                         width="124"
                         height="30"
                         alt="Skymatix logo"
                         class="footer-img">
                </a>
            </div>
        </div>
        {% block end-script %}
        {% endblock end-script %}
    </body>
</html>

checklist/templates/checklist/detail.html
{% extends "checklist/base.html" %}
{% load static %}
{% load environment_tags %}
{% block title %}
    Smart Checklist
{% endblock title %}
{% block script %}
    <script src="{% static 'checklist/toggle_switches.js' %}"></script>
    <script>
    function GetSelected() {
        // Reference the Table.
        var grid = document.getElementById("Table1");

        // Reference the CheckBoxes in Table.
        var checkBoxes = grid.getElementsByClassName("clCheckBox");

        // Loop through the CheckBoxes.
        for (var i = 0; i < checkBoxes.length; i++) {
            var row = checkBoxes[i].parentElement.parentElement;

            row.classList.remove("active-row"); 

            // Check if the checkbox is checked.
            if (checkBoxes[i].checked) {
                row.classList.add("checked-row");
                
                var lastChecked = i;
            } else {
                row.classList.remove("checked-row");

             
            }
        }

        // Highlight the next row as active-row.
        if ((lastChecked + 1) < checkBoxes.length) {
            checkBoxes[lastChecked + 1].parentElement.parentElement.classList.add("active-row");
        }
    }

    function switchCheckbox(id) {
        var checkbox = document.getElementById(id)
        checkbox.checked=!checkbox.checked
        GetSelected(); 
            
    }


    </script>
{% endblock script %}
{% block content %}
    <div class="fit-content">
        <legend>
            {% csrf_token %}
            <h1>{{ procedure.title }}</h1>
            {% if request.session.dual_mode %}
                {% include "checklist/toggle_switches.html" %}
            {% endif %}
        </legend>
        <div class="table-div">
            <table id="Table1" class="styled-table">
                <thead>
                    <tr>
                        <th>Done</th>
                        <th>Item</th>
                        {% if request.session.dual_mode %}<th>Role</th>{% endif %}
                        <th>Check</th>
                        <th class="attributes-column">attributes</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in check_items %}
                        {% if forloop.counter == 1 %}
                            <tr id="row{{ forloop.counter }}"
                                class="active-row {% if item.lowlight %}lowlight{% endif %}"
                                data-role="{{ item.role }}">
                            {% else %}
                                <tr id="row{{ forloop.counter }}"
                                    {% if item.lowlight %}class="lowlight"{% endif %}
                                    data-role="{{ item.role }}">
                                {% endif %}
                                <td>
                                    <input type="checkbox"
                                           id="name{{ item.id }}"
                                           name="name{{ item.id }}"
                                           class="clCheckBox"
                                           onclick="GetSelected()">
                                </td>
                                <td class="text-cel" onclick="switchCheckbox('name{{ item.id }}')">{{ item.item }}</td>
                                {% if request.session.dual_mode %}
                                    <td class="text-cel"  onclick="switchCheckbox('name{{ item.id }}')">{{ item.role }}</td>
                                {% endif %}
                                <td class="text-cel descrip"
                                    onclick="switchCheckbox('name{{ item.id }}')">{{ item.setting }}</td>
                                <td class="attributes-column"
                                    onclick="switchCheckbox('name{{ item.id }}')">
                                    <ul class="cl-taglist">
                                        {% for attrib in item.attributes.all %}
                                            {% include "checklist/attrib_detail.html" %}
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="btn-bar">
                    {% if prevproc %}
                        <a class="btn btn-left"
                           href="{% url 'checklist:detail' prevproc.slug %} ">Prev</a>
                    {% endif %}
                    {% if nextproc %}
                        <a class="btn btn-right"
                           href=" {% url 'checklist:detail' nextproc.slug %} ">Next</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endblock content %}
    {% block footer %}
        query time: {{ proctime }} s
        {% if 'DEBUG'|setting == True %}{{ request.session.attrib }}{% endif %}
    {% endblock footer %}
    {% block end-script %}
        <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Call GetSelected() on page load
            GetSelected();

            // Override the updateSessionRoles callback to include a page reload
            const pilotRoleSwitch = document.getElementById("pilot_role");
            const captainRoleSwitch = document.getElementById("captain_role");

            if (pilotRoleSwitch && captainRoleSwitch) {
                pilotRoleSwitch.addEventListener("change", () => {
                    updateSessionRoles(() => {
                        location.reload(); // Reload the page after updating the session
                    });
                });

                captainRoleSwitch.addEventListener("change", () => {
                    updateSessionRoles(() => {
                        location.reload(); // Reload the page after updating the session
                    });
                });
            }
        });
        </script>
    {% endblock end-script %}

checklist/templates/checklist/index.html
{% extends "checklist/base.html" %}
{% load static %}
{% block title %}
    Procedure overview
{% endblock title %}
{% block script %}
{% endblock script %}
{% block content %}
    <div class="fit-content">
        <legend>
            {% csrf_token %}
            <h1>Procedure overview</h1>
            {% if request.session.dual_mode %}
                {% include "checklist/toggle_switches.html" %}
            {% endif %}
        </legend>
        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}
        {% if procedure_list %}
            <div class="table-div">
                <table id="Table1" class="styled-table">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Procedure</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for proc in procedure_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    <a href="{{ proc.get_absolute_url }} ">{{ proc.title }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="btn-bar">
                    <a class="btn btn-right" href=" {% url 'checklist:export' %} ">Export xCheckList</a>
                </div>
            </div>
        {% else %}
            <p>No items are available.</p>
        {% endif %}
    </div>
{% endblock content %}
{% block end-script %}
    <script src="{% static 'checklist/toggle_switches.js' %}" defer></script>
{% endblock end-script %}

checklist/templates/checklist/profile.html
{% extends "checklist/base.html" %}
{% load environment_tags %}
{% block title %}
    Session profile
{% endblock title %}
{% block script %}
    <script>
    document.addEventListener("DOMContentLoaded", function () {
        const clearButton = document.getElementById("clear-button");
        const clearForm = document.getElementById("clear-form");
        const clearCookieInput = document.getElementById("clear-cookie-input");

        clearButton.addEventListener("click", function (event) {
            const cookiePresent = clearButton.dataset.cookiePresent === "true";

            if (cookiePresent) {
                // Prevent the form from submitting immediately
                event.preventDefault();

                // Show a confirmation dialog
                const confirmClearCookie = confirm(
                    "The SimBrief cookie is present. Do you also want to clear the cookie?"
                );

                // Update the hidden input based on the user's choice
                clearCookieInput.value = confirmClearCookie ? "1" : "0";

                // Submit the form after updating the input
                clearForm.submit();
            }
        });
    });
    </script>
{% endblock script %}
{% block content %}
    <div class="fit-content">
        <fieldset class="no-border">
            <legend>
                <h1>Specify session profile</h1>
            </legend>
            {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
            {% endif %}
            <div class="profile-section">
                {% if simbrief_id and error_message is None %}
                    <p class="styled-text">
                        Departure Airport: <strong>{{ origin }}</strong>,
                        Alt: <strong>{{ elevation }}</strong>,
                        RWY:<strong>{{ runway }} ({{ rwy_length }})</strong>,
                        Temp:<strong>{{ temperature }}</strong>
                    </br>
                    Departure setting - Flaps: <strong>{{ flap_setting }}</strong> Bleed: <strong>{{ bleed_setting }}</strong>
                    (based on Simbrief plan, not a proper takeoff performance calculation)
                </p>
            {% else %}
                <p class="styled-text">
                    <form action="{% url 'checklist:profile' %}"
                          method="post"
                          class="profile-form">
                        {% csrf_token %}
                        <label for="simbrief_id" class="form-label">Simbrief ID:</label>
                        <input type="text"
                               id="simbrief_id"
                               name="simbrief_id"
                               value="{{ simbrief_id }}"
                               class="form-input">
                        <label for="remember_me" class="form-label form-right">
                            <input type="checkbox"
                                   id="remember_me"
                                   name="remember_me"
                                   value="1"
                                   class="form-checkbox"
                                   {% if remember_me %}checked{% endif %}>
                            Remember me (uses cookies)
                        </label>
                        <input type="submit" value="Get Plan" class="btn btn-right">
                    </form>
                </p>
            {% endif %}
        </div>
        <form action="{% url 'checklist:update_profile' %}" method="post">
            {% csrf_token %}
            <table id="Table1" class="styled-table">
                <thead>
                    <tr>
                        <th>Check</th>
                        <th>Profile attribute</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="checkbox"
                                   name="dual_mode"
                                   id="dual_mode"
                                   value="True"
                                   {% if request.session.dual_mode %}CHECKED{% endif %} />
                        </td>
                        <td>
                            <label for="dual_mode">Two Pilots</label>
                        </td>
                        <td>
                            <label for="dual_mode">Check this to enable PF/PM indicators</label>
                        </td>
                    </tr>
                    {% for check in attributes.all %}
                        {% if check.show %}
                            <tr>
                                <td>
                                    <input type="checkbox"
                                           name="attributes"
                                           id="{{ forloop.counter }}"
                                           value="{{ check.id }}"
                                           {% if check.id in request.session.attrib %}CHECKED{% endif %} />
                                </td>
                                <td>
                                    <label for="{{ forloop.counter|escape }}">{{ check.title }}</label>
                                </td>
                                <td>
                                    <label for="{{ forloop.counter }}">{{ check.description }}</label>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <input class="btn btn-right" type="submit" value="Next">
        </form>
        <!-- Separate form for the "Clear" button -->
        <form action="{% url 'checklist:profile' %}"
              method="post"
              class="inline"
              id="clear-form">
            {% csrf_token %}
            <input type="hidden" name="Clean" value="1">
            <input type="hidden" name="clear_cookie" value="0" id="clear-cookie-input">
            <button type="submit"
                    class="btn btn-left"
                    id="clear-button"
                    data-cookie-present="{% if request.COOKIES.simbrief_pilot_id %}true{% else %}false{% endif %}">
                Clear
            </button>
        </form>
    </fieldset>
</div>
{% endblock content %}
{% block footer %}
    {% if 'DEBUG'|setting == True %}{{ request.session.attrib }}{% endif %}
{% endblock footer %}

checklist/templates/checklist/toggle_switches.html
<!-- filepath: c:\Code\SmartTrainingChecklist\checklist\templates\checklist\toggle_switches.html -->
<div class="toggle-switches">
    <div class="toggle-group left">
        <label for="pilot_role">Pilot Flying</label>
        <label class="switch">
            <input type="checkbox"
                   name="pilot_role"
                   id="pilot_role"
                   value="PM"
                   {% if request.session.pilot_role == "PM" %}checked{% endif %}>
            <span class="slider"></span>
        </label>
        <label for="pilot_role">Pilot Monitoring</label>
    </div>
    <div class="toggle-group middle">
        <label for="dual">Dual Operating</label>
    </div>
    <div class="toggle-group right">
        <label for="captain_role">Captain</label>
        <label class="switch">
            <input type="checkbox"
                   name="captain_role"
                   id="captain_role"
                   value="FO"
                   {% if request.session.captain_role == "FO" %}checked{% endif %}>
            <span class="slider"></span>
        </label>
        <label for="captain_role">First Officer</label>
    </div>
</div>